FORMAT: 1A
HOST: http://www.google.com

# DAP Services a.s. - Softskillers API

API pro aplikaci Softskillers.

##Allowed HTTPs requests:

- `POST` - Creates or updates a resource
- `PUT` - Updates a resource
- `GET` - Retrieves a resource or list of resources
- `DELETE` - Delete a resource

##Typical Server Responses

- 200 `OK` - The request was successful (some API calls may return 201 instead).
- 201 `Created` - The request was successful and a resource was created.
- 204 `No Content` - The request was successful but there is no representation to return (that is, the response is empty).
- 400 `Bad Request` - The request could not be understood or was missing required parameters.
- 401 `Unauthorized` - Authentication failed or user does not have permissions for the requested operation.
- 403 `Forbidden` - Access denied.
- 404 `Not Found` - Resource was not found.
- 405 `Method Not Allowed` - Requested method is not supported for the specified resource.
- 429 `Too Many Requests` - Exceeded API limits. Pause requests, wait one minute, and try again.
- 503 `Service Unavailable` - The service is temporary unavailable. Try again later.

# API root [/]

Bez atributů, vrací `403`.

## Požadavek na root [GET]

+ Response 403

# Group Account

Práce s účtem uživatele.

## Users Login [/account/login]

Autentizace. Všechny http metody kromě **POST** vrací http status code `405`.

### Login User [POST]

role: businessman, business_partner

Přihlašování.

Seznam json atributů:

- username (required, string) - uživatelské jméno
- password (required, string) - heslo
- app_id (required, string) - id aplikace, do které se uživatel přihlašuje.

+ Request (application/json)
    + Headers

            Accept: application/json

    + Body

            {
                "login": "user@yourdomain.com",
                "password": "good_password",
                "app_id": "APPID"
            }

    + Schema

            {
                "type": "object",
                "required": true,
                "properties": {
                    "username": {
                        "type": "string",
                        "required": true
                    },
                    "password": {
                        "type": "string",
                        "required": true
                    },
                    "app_id": {
                        "type": "string",
                        "required": true
                    }
                }
            }
+ Response 200 (application/json)

    + Header

            Access-Control-Allow-Origin: *

    + Body

            {
                "user_id": 12312334,
                "profile": "/account/profile/{user_id}",
                "token": "security_token",
                "role":"business_partner",
                "first_name":"first_name",
                "last_name":"last_name"
            }

+ Response 401 (Unauthorized)

    + Header

            Access-Control-Allow-Origin: *

    + Body

            {
                "messages": 
                    {"i18nKey":"error_code_login","type":"error"}
            }

## Users Login [/account/loginbad]
#
### Login User [POST]

+ Response 401 (Unauthorized)

    + Header

            Access-Control-Allow-Origin: *

    + Body

            {
                "error": {
                    "message": "Chybové hlášení pro autentizaci."
                }
            }



## Operace pro zobrazení uživatele. [/account/{user_id}]
### List all accounts [GET]
+ Response 200 (application/json)

    + Header

            Access-Control-Allow-Origin: *

    + Body

            {
                "customer_id":"customer_id",
                "first_name": "first_name",
                "last_name": "last_name",
                "company_name": "company_name",
                "email": "email@email.cz",
                "address": "address",
                "country_code": {"name": "ISO country code","id": 1},
                "language_code": {"name": "ISO language code","id": 1},
                "phone_number": "123 123 1234",
                "login": "login_name",
                "vat_number": "vat_number",
                "licence_start": "25.2.2014",
                "licence_end": "25.2.2015",
                "ordered":true
            }

### Create new account [PUT]

> TODO jaký je rozdíl mezi [PUT] account a [POST] account/registration?

+ Request (application/json)

    + Header

            Access-Control-Allow-Origin: *

    + Body

            {
                "first_name": "first_name",
                "last_name": "last_name",
                "company_name": "company_name",
                "email": "email",
                "address": "address",
                "country_code": {"name": "ISO country code","id": 1},
                "language_code": {"name": "ISO language code","id": 1},
                "phone_number": "123 123 1234",
                "login": "login_name",
                "vat_number": "vat_number",
                "password": "password",
                "verify_password": "verify_password"
            }

+ Response 200 (application/json)

            {
                "account_id": 12312334,
                "profile": "/account/profile/{user_id}"
            }

+ Response 400 (application/json)

            {
                "error": {
                    "message": "Chybové hlášení pro upravu uživatele.",
                    "error_code": "error.code.updateaccount"
                }
            }

## Registrace uživatele [/account/registration]

### Register [POST]

+ Request (application/json)

    + Header

            Access-Control-Allow-Origin: *

    + Body

            {
                "first_name": "first_name",
                "last_name": "last_name",
                "company_name": "company_name",
                "email": "email",
                "address": "address",
                "country_code":"ISO country code",
                "language_code": "ISO language code",
                "phone_number": "123 123 1234",
                "login": "login_name",
                "password": "PASSWORD",
                "verify_password": "PASSWORD",
                "vat_number": "vat_number"
            }


+ Response 200 (application/json)

            {
                "user_id": 12312334,
                "profile": "/account/profile/{user_id}"
            }

+ Response 400 (application/json)

            {
                "error": {
                    "message": "Chybové hlášení pro vytvoření uživatele.",
                    "error_code": "error.code.registration"
                }
            }

## Users Login [/account/registrationconfirm]

> TODO url by mohla být /account/registration/confirm

Potvrzení registrace uživatele. Posílá se klíč, který uživatel dostal (pravděpodobně do emailu v potvrzovacím linku). V případě, že požadavek není validní - neexistující klíč, uživatel je již aktivovaný se vrací error json.

### Login User [POST]

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

            {
                "key": "confirmation_key"
            }

+ Response 200 (application/json)

    + Header

            Access-Control-Allow-Origin: *

    + Body

            {
                "user_id": 12312334,
                "profile": "/account/profile/{user_id}"
            }

# Seznam školení uživatele [/account/{user_id}/training]

Práce se školeními uživatele. Autorizovaný resource.

> TODO training vs trainings.

## GET

Seznam školení uživatele.

+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *

    + Body

            [
                {
                    "training_id": 1,
                    "i18nkey": "nls.training.name.key",
                    "status": "ORDERED"
                },
                {
                    "training_id": 2,
                    "i18nkey": "nls.training.name.key",
                    "status": "NOT_ORDERED"
                },
                {
                    "training_id": 3,
                    "i18nkey": "nls.training.name.key",
                    "status": "WAITING"
                }
            ]

# Konkretni školení uživatele [/account/{user_id}/training/{training_id}]

Práce se školeními uživatele. Autorizovaný resource.

> TODO Pravděpodobně samostatný resource pro app

## GET

Seznam školení uživatele.

+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *

    + Body

                {
                    "training_id": 1,
                    "name": "nls.training.name.key",
                    "status": "NOT_ORDERED"
                }

## Objednani trenings [/account/{user_id}/training/{training_id}/order]
### order [POST]

Objednání školení uživatele. Výsledkem je odeslání emailu administrátorovi s žádostí o školení.

+ Request (application/json)

    + Headers

            Access-Control-Allow-Origin: *

    + Body

            {
                "training_id": 1,
                "message":"message_text"
            }

+ Response 200

            {
                "training_id": 1,
                "profile": "/account/profile/{user_id}"
            }

## Potvrzeni trenings adminem [/account/{user_id}/training/{training_id}/confirm]
### confirm [POST]

Potvrzeni školení adminem.

+ Request (application/json)

    + Headers

            Access-Control-Allow-Origin: *

    + Body

            {
                "training_id": 1,
                "message":"message_text"
            }

+ Response 200

            {
                "training_id": 1,
                "profile": "/account/profile/{user_id}"
            }

## Languages Collection [/language/en]
### List all Languages [GET]
+ Response 200 (application/json)

    + Header

            Accept: application/json

    + Body

            [{
                "name": "EN",
                "id": 1
            }, {
                "name": "DE",
                "id": 2
            }, {
                "name": "CZE",
                "id": 3
            }]

## Countries Collection [/country/en]
### List all Countries [GET]
+ Response 200 (application/json)

    + Header

            Accept: application/json

    + Body

            [{
                "name": "USA",
                "id": 1
            },{
                "name": "Canada",
                "id": 2
            }]

## Seznam vsech zakazniku pro konkretniho business partnera [/account/{user_id}/customer]
### List all Customers [GET]
+ Response 200 (application/json)

    + Header

            Access-Control-Allow-Origin: *

    + Body

            [{
                "customer_id": "customer_id_1",
                "company_name": "company_name",
                "date": "date",
                "city": "city",
                "country_code": "ISO country code"
            },{
                "customer_id": "customer_id_2",
                "company_name": "company_name",
                "date": "date",
                "city": "city",
                "country_code": "ISO country code"
            }]

### Vytvoreni noveho zakaznika [POST]

+ Request (application/json)

    + Header

            Access-Control-Allow-Origin: *

    + Body

            {
                "company_name": "company_name",
                "scanner_language":{"name": "EN_scan","id": 1},
                "name": true,
                "surname": false,
                "email":true,
                "department": false,
                "department_name": "department_name",
                "item": true,
                "item_name": "item_name"
            }


+ Response 200 (application/json)

            {
                "customer_id": 12312334,
                "profile": "/account/profile/{user_id}"
            }

+ Response 400 (application/json)

            {
                "error": {
                    "message": "Chybové hlášení pro vytvoření zakaznika.",
                    "error_code": "error.code.createcustomer"
                }
            }

## Detail konkretniho zakaznika pro konkretniho business partnera [/account/{user_id}/customer/{customer_id}]
### Detail Customer [GET]
+ Response 200 (application/json)

    + Header

            Access-Control-Allow-Origin: *

    + Body

            {
                "customer_id": "customer_id_1",
                "company_name": "company_name",
                "date": "date",
                "city": "city",
                "country_code": "ISO country code",
                "scanner_language":{"name": "EN_scan","id": 1},
                "scanner_link":"http://url_scanner",
                "name":true,
                "surname":false,
                "department":true,
                "department_name":"department_name",
                "item":true,
                "item_name":"item_name"
            }

### Editace zakaznika [PUT]

+ Request (application/json)

    + Header

            Access-Control-Allow-Origin: *

    + Body

            {
                "company_name": "company_name",
                "scanner_language":{"name": "EN_scan","id": 1},
                "name": true,
                "surname": false,
                "email":true,
                "department": true,
                "department_name": "department_name",
                "item": true,
                "item_name": "item_name"
            }


+ Response 200 (application/json)

            {
                "customer_id": 12312334,
                "profile": "/account/profile/{user_id}"
            }

+ Response 400 (application/json)

            {
                "error": {
                    "message": "Chybové hlášení pro editaci zakaznika.",
                    "error_code": "error.code.editcustomer"
                }
            }


## Seznam scanu konkretniho zakaznika konkretniho business partnera [/account/{user_id}/customer/{customer_id}/result]
### List Diag Result [GET]
+ Response 200 (application/json)

    + Header

            Access-Control-Allow-Origin: *

    + Body

            [{
                "diag_result_id": "diag_result_id_1",
                "name": "name_1",
                "surname": "surname",
                "email":"email@email.cx",
                "department_name": "department1",
                "item_name":"item_name",
                "birth_year": "birth_year",
                "scan_date": "scan_date",
                "customer_id":"customer_id"
            },{
                "diag_result_id": "diag_result_id_2",
                "name": "name_2",
                "surname": "surname",
                "email":"email@email.cx",
                "department_name": "department2",
                "item_name":"item_name",
                "birth_year": "birth_year",
                "scan_date": "scan_date",
                "customer_id":"customer_id"
            },{
                "diag_result_id": "diag_result_id_21",
                "name": "name_21",
                "surname": "surname",
                "email":"email@email.cx",
                "department_name": "department3",
                "item_name":"item_name",
                "birth_year": "birth_year",
                "scan_date": "scan_date",
                "customer_id":"customer_id"
            },{
                "diag_result_id": "diag_result_id_22",
                "name": "name_22",
                "surname": "surname",
                "email":"email@email.cx",
                "department_name": "department1",
                "item_name":"item_name",
                "birth_year": "birth_year",
                "scan_date": "scan_date",
                "customer_id":"customer_id"
            },{
                "diag_result_id": "diag_result_id_31",
                "name": "name_31",
                "surname": "surname",
                "email":"email@email.cx",
                "department_name": "department2",
                "item_name":"item_name",
                "birth_year": "birth_year",
                "scan_date": "scan_date",
                "customer_id":"customer_id"
            },{
                "diag_result_id": "diag_result_id_32",
                "name": "name_32",
                "surname": "surname",
                "email":"email@email.cx",
                "department_name": "department3",
                "item_name":"item_name",
                "birth_year": "birth_year",
                "scan_date": "scan_date",
                "customer_id":"customer_id"
            },{
                "diag_result_id": "diag_result_id_25",
                "name": "name_25",
                "surname": "surname",
                "email":"email@email.cx",
                "department_name": "department1",
                "item_name":"item_name",
                "birth_year": "birth_year",
                "scan_date": "scan_date",
                "customer_id":"customer_id"
            }]

## Seznam lidi konkretniho zakaznika konkretniho business partnera [/account/{user_id}/customer/{customer_id}/persons]
### List department [GET]
+ Response 200 (application/json)

    + Header

            Access-Control-Allow-Origin: *

    + Body

            [{
                "person_id": 1,
                "name": "name_1",
                "birth_year": "birth_year",
                "department": "department1"
            },{
                "person_id": 2,
                "name": "name_2",
                "birth_year": "birth_year",
                "department": "department1"
            },{
                "person_id": 3,
                "name": "name_3",
                "birth_year": "birth_year",
                "department": "department2"
            },{
                "person_id": 4,
                "name": "name_4",
                "birth_year": "birth_year",
                "department": "department2"
            },{
                "person_id": 5,
                "name": "name_5",
                "birth_year": "birth_year",
                "department": "department3"
            },{
                "person_id": 6,
                "name": "name_6",
                "birth_year": "birth_year",
                "department": "department3"
            }]

## Seznam departmentu konkretniho zakaznika konkretniho business partnera [/account/{user_id}/customer/{customer_id}/departments]
### List department [GET]
+ Response 200 (application/json)

    + Header

            Access-Control-Allow-Origin: *

    + Body

            [{
                "department_id": 1,
                "department": "department1"
            },{
                "department_id": 2,
                "department": "department2"
            },{
                "department_id": 3,
                "department": "department3"
            }]

## Languages Collection [/scannerlanguage]
### List all Scanner Languages [GET]
+ Response 200 (application/json)

    + Header

            Access-Control-Allow-Origin: *

    + Body

            [{
                "name": "EN_scan",
                "id": 1
            }, {
                "name": "DE_scan",
                "id": 2
            }, {
                "name": "CZE_scan",
                "id": 3
            }]

## Registrace uživatele [/contact]
### Register [POST]

+ Request (application/json)

    + Header

            Access-Control-Allow-Origin: *

    + Body

            {
                "name": "name",
                "email": "email",
                "subject": "subject",
                "message": "message"
            }


+ Response 200 (application/json)

            {
                "contact": "OK",
                "profile": "/account/profile/{user_id}"
            }

+ Response 400 (application/json)

            {
                "error": {
                    "message": "Chybové hlášení pro odeslani zpravy.",
                    "error_code": "error.code.sendmessage"
                }
            }

## Download pdf [/download/{hash_result}/{token}]
### Download [GET]

            
+ Response 200

    + Header

            Content-Type: application/pdf
            Content-Disposition: attachment; filename="jump.pdf"
            Access-Control-Allow-Origin: *

    + Body

            text 


## Seznam nebo jednoho person konkretniho zakaznika konkretniho business partnera [/account/{user_id}/customer/{customer_id}/generateresult]
### List Diag Group Result [POST]
+ Request (application/json)


            [
                "diag_result_id_2",
                "diag_result_id_21",
                "diag_result_id_32",
                "person_id_1"
            ]
            
+ Response 402

    + Header

            Access-Control-Allow-Origin: *

    + Body

            {
                "messages": 
                    {"i18nKey":"error_code_groupresult","type":"error"}
            }
            
+ Response 200 (application/json)

    + Header

            Access-Control-Allow-Origin: *

    + Body

            {
                "hash_result": "hdkdirrff15487",
                "profile": "/account/profile/{user_id}"
            }

+ Response 400 (application/json)

    + Header

            Access-Control-Allow-Origin: *

    + Body

            {
                "error": {
                    "message": "Chybové hlášení pro generovani group result zakaznika.",
                    "error_code": "error.code.groupresult"
                }
            }

## Seznam business partneru konkretniho obchodnika [/businesspartner/{user_id}]
### List businesspartner [GET]
+ Response 200 (application/json)

    + Header

            Access-Control-Allow-Origin: *

    + Body

            [{
                "company_id": "company_id1",
                "company_name": "company_name1",
                "date": "12.12.2014",
                "email": "email@email.cz",
                "phone":"123456789"
            },{
                "company_id": "company_id2",
                "company_name": "company_name2",
                "date": "12.12.2014",
                "email": "email@email.cz",
                "phone":"123456789"
            },{
                "company_id": "company_id3",
                "company_name": "company_name3",
                "date": "12.12.2014",
                "email": "email@email.cz",
                "phone":"123456789"
            }]

## Licence - history [/account/{user_id}/licence]
### List all licences [GET]
+ Response 200 (application/json)

    + Header

            Access-Control-Allow-Origin: *

    + Body

            [{
                "licence_start": "25.2.2014",
                "licence_end": "25.2.2015",
                "licence_when":"2.2.2014"
            },{
                "licence_start": "25.2.2013",
                "licence_end": "25.2.2014",
                "licence_when":"2.2.2013"
            }]


### Create new licence [POST]
+ Request (application/json)

            {
                "licence_start": "25.2.2013",
                "licence_end": "25.2.2014"
            }

+ Response 200 (application/json)

    + Header

            Access-Control-Allow-Origin: *

    + Body

            {
                "messages": 
                    {"i18nKey":"orderlicense_license_is_confirmed","type":"success"}
            }

## Licence - order [/account/{user_id}/licence/order]
Výsledkem je email adminovi ohledně objednání licence (v emailu bude i zpráva, kterou uživatel napsal) a email osobě s potvrzením objednávky
### Order licence [POST]

+ Request (application/json)

            {
                "message": "message"
            }

+ Response 200 (application/json)

    + Header

            Access-Control-Allow-Origin: *

    + Body

            {
                "messages": 
                    {"i18nKey":"orderlicense_success_code","type":"success"}
            }
            
+ Response 400 

    + Header

            Access-Control-Allow-Origin: *

    + Body

            {
                "messages": 
                    {"i18nKey":"orderlicense_error_code","type":"error"}
            }
            

## Partner - order [/order/partner]
### New order [POST]
Vytvoreni nebo editace nove obednavky. Zalezi jestli je vyplneno order_id

+ Request (application/json)

    + Header

            Access-Control-Allow-Origin: *
            X-Authorization: 12124-545-asdf

    + Body
       
            {
                "order_id": 1,
                "scanner": {
                    "first_name": {
                        "values": null,
                        "label": null,
                        "selected": true
                    },
                    "last_name": {
                        "values": null,
                        "label": null,
                        "selected": true
                    },
                    "department": {
                        "values": "dep1;dep2;dep3",
                        "label": null,
                        "selected": true
                    },
                    "custom_item": {
                        "values": null,
                        "label": "Name of our favorite pet.",
                        "selected": true
                    }
                },
                "name": "New partner order",
                "consultant_id":1,
                "valid_to":121546516,
                "scanner_language":"en"
                "send_instruction": true,
                "send_result_to_person": true,
                "send_results_to_consultant": true,
                
                "persons": [
                    {
                      "newEmail": "a@aa.aa",
                      "department": "a"
                    },
                    {
                      "newEmail": "aa@aa.aa"
                    },
                    {
                      "newEmail": "b@b.bb"
                    }
                ],
                "departments": [
                    "a",
                    "b",
                    "c"
                ]
            }
        
+ Response 200 (application/json)

    + Header

            Access-Control-Allow-Origin: *

    + Body

            {
                "messages": 
                    {"i18nKey":"order_success_code","type":"success"}
            }
            
+ Response 400 

    + Header

            Access-Control-Allow-Origin: *

    + Body

            {
                "messages": 
                    {"i18nKey":"order_bad_request_code","type":"error"}
            }
            
### Order licence [GET]
Vrácení všech objednávek uživatele


+ Request (application/json)

    + Header

            Access-Control-Allow-Origin: *
            X-Authorization: 12124-545-asdf

    + Body
       
        
+ Response 200 (application/json)

    + Header

            Access-Control-Allow-Origin: *

    + Body

            {
                "id":1,    
                "name": "New partner order",
                "insert_time": 1231564,
                "valid_to": 121546516,
                "order_status": "open",
                "scanned_count": 12,
                "total_count": 50
            },
            {
                "id":2,    
                "name": "Second partner order",
                "insert_time": 1431564,
                "valid_to": 161546516,
                "order_status": "open",
                "scanned_count": 4,
                "total_count": 50
            }
       
## Licence - order [/order/partner/{order_id}]
### Order licence [GET]
Načtení detailu objednávky

+ Request (application/json)

    + Header

            Access-Control-Allow-Origin: *
            X-Authorization: 12124-545-asdf

+ Response 200 (application/json)
    
    + Header

            Access-Control-Allow-Origin: *
    
    + Body
       
            {
                "scanner": {
                    "first_name": {
                        "values": null,
                        "label": null,
                        "selected": true
                    },
                    "last_name": {
                        "values": null,
                        "label": null,
                        "selected": true
                    },
                    "department": {
                        "values": "dep1;dep2;dep3",
                        "label": null,
                        "selected": true
                    },
                    "custom_item": {
                        "values": null,
                        "label": "Name of our favorite pet.",
                        "selected": true
                    }
                },
                "name": "New partner order",
                "consultant_id":1,
                "valid_to":121546516,
                "scanner_language":"en",
                "send_instruction": true,
                "send_result_to_person": true,
                "send_results_to_consultant": true,
                
                "persons": [
                    {
                      "email": "a@aa.aa",
                      "department": "a"
                    },
                    {
                      "email": "aa@aa.aa",
                      "newEmail":"ab@aa.aa"
                    },
                    {
                      "email": "b@b.bb"
                    }
                ],
                "departments": [
                    "a",
                    "b",
                    "c"
                ],
                "scanner_languages": [
                    {
                      "i18nKey": "en",
                      "id": "en"
                    },
                    {
                      "i18nKey": "cs",
                      "id": "cs"
                    }
                  ],
                  "consultants": [
                    {
                      "id": 0,
                      "email": "consultant1@example.com",
                      "firstName": "Karel",
                      "lastName": "Novak"
                    },
                    {
                      "id": 2,
                      "email": "consultant2@example.com",
                      "firstName": "Renata",
                      "lastName": "Svobodova"
                    }
                ]
            }